### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [dadleyy/marlow#93]
I found that this project already [supports Go modules](https://github.com/dadleyy/marlow/blob/master/go.mod). The latest version committed on 26 Jun 2018, and the [tags](https://github.com/dadleyy/marlow/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/dadleyy/marlow v0.0.0-20200105141552-3c08ec96fc16
```
Else the mod file shows something like `github.com/dadleyy/marlow v0.0.0-20200105141552-3c08ec96fc16` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@kak-tus  Could you help me review this issue? Thx :p

**Comment by kak-tus** [comment]
@KateGo520 I am not a contributor for this project, but semver is looks good for me, and I prefer to use it in my projects. But change versioning model - only author can do tis here.

**Comment by KateGo520** [comment]
@kak-tus  Thank you for your reply!
@dadleyy  Could you help me review this issue? Thx :p

**Comment by dadleyy** [comment]
@KateGo520 yes! I am all for semver; I think I may move forward with the splitting-the-repo approach I mentioned in #89. I'm not actively maintaining this repo anymore but I just created the `github.com/marlow` org. At some point this week I will figure out a way to move the cli and lib code into two distinct repos under that org. At that point, once everything looks 👌, we can just cut `v1.0.0` tags, since I _feel_ like this has been "stable" for a while now.
 
Does that sound like a good plan?

**Comment by KateGo520** [comment]
@dadleyy  Tag v1.0.0 sounds OK for me. Thank you for your reply!

**Comment by dadleyy** [comment]
@KateGo520 I just finished copying the bits of this repo over to [the marlow org](https://github.com/marlow). I think all thats left to do is to create the `v1.0.0` tags in each one of those repos, but I'm not 100% sure; is there anything specific that would need to be done with `go` itself?

**Comment by KateGo520** [comment]
@dadleyy  It seems nothing need to do. When the version is upgraded to V2 +, the version number should be added in the module path, "github.com/dadleyy/marlow/vN" (N: the version major number).
